version: "3.8"
name: "<docker-compose-name>"
services:
    <front>:
        image: <img>:<version>
        ports:
            - "<external_port>:<internal_port>"
        volumes:
            - <host_path>:<client_path>
        networks:
            - <network_name>
        restart: unless-stopped
    <back>:
        build:
            context: .
            dockerfile: <Dockerfile>
        volumes:
            - <host_path>:<client_path>
        ports:
            - ":<client_port>"
        extra_hosts:
            - <host_domain_or_ip>:<client_ip> //example= some-host:10.10.10.10
        networks:
            - <network_name>
        restart: unless-stopped
networks:
    <network_name>:
        driver: bridge
